package com.lia.BitManipulation;

/**
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 *
 * Created by liqu on 10/9/16.
 */
public class FindTheDifference_389 {
    // Bit XOR solution
    public char findTheDifference(String s, String t) {
        char[] sc = s.toCharArray();
        char[] tc = t.toCharArray();
        char bit = 0;
        for (int i = 0; i < sc.length; i++) {
            bit ^= sc[i];
            bit ^= tc[i];
        }

        bit ^= tc[tc.length - 1];
        return bit;
    }
}
